services:

  knn:
    build:
      context: .
      dockerfile: Dockerfile.knn
    networks:
      - backend
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/ready"]
      interval: 5s
      timeout: 3s
      retries: 60 
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "220MB"

  api1:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - KNN_SERVICE_URL=http://knn:8080
      - PORT=8081
    networks:
      - backend
    depends_on:
      knn:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.225"
          memory: "60MB"

  api2:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - KNN_SERVICE_URL=http://knn:8080
      - PORT=8081
    networks:
      - backend
    depends_on:
      knn:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.225"
          memory: "60MB"

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "10MB"

networks:
  backend:
    driver: bridge
