volumes:
  sockets:

networks:
  backend:
    driver: bridge

services:
  haproxy:
    image: haproxy:3.3
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/tmp/sockets
    depends_on:
      - api1
      - api2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"

  api1:
    image: ghcr.io/marcoant007/rinha-backend-2026-api:v14
    environment:
      - INSTANCE_ID=1
    volumes:
      - sockets:/tmp/sockets
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "162MB"

  api2:
    image: ghcr.io/marcoant007/rinha-backend-2026-api:v14
    environment:
      - INSTANCE_ID=2
    volumes:
      - sockets:/tmp/sockets
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "162MB"
